name: BW-Bicep-KeyVault-Deploy-$(Date:yyyyMMdd).$(Rev:r)

resources:
  repositories:
    - repository: templates
      type: git
      name: ais/ci-cd-patterns
      ref: refs/tags/2.2.0

  pipelines:
    #do not change (used in pipeline resource variables)
    - pipeline: infra-build-pipeline
      source: BW-Bicep-KeyVault-Build
      trigger:
        branches:
          include: #only trigger when source pipeline is run on these branches
            - main
            - release/*
            - hotfix/*

trigger: none

extends:
  template: azure-resources-bicep/az-deploy.yml@templates
  parameters:
    agentPoolDev: 'Azure Pipelines'
    agentPoolProd: 'Azure Pipelines'
    artifactNamePrefix: 'azinfra-kv'
    artifactsFeedPrefix: 'BW/bw'
    deployEnabled: true
    serviceConnectionDevTest: 'azure.devtest-BW'
    serviceConnectionProd: 'azure.prd-BW'
    serviceConnectionUat: 'azure.uat-BW'
    promoteVerifyDependsOn:
      - AZInfraKVBuild01
    promoteReleaseDependsOn:
      - AZInfraKVUat01

    deployBuild:
      - stageName: AZInfraKVBuild01
        displayName: "Deploy to Dev"
        environment: "BW-DevTest"
        resourceGroupName: 'rg-devtest-ase-bw'
        location: 'australiasoutheast'
        bicepParams: 'dev-kv'
        deploymentMode: 'Incremental'
        deploymentName: 'bw-kv-dev-$(Build.BuildNumber)-$(System.StageAttempt)'

    deployVerify:
      - stageName: AZInfraKVUat01
        displayName: "Deploy to UAT"
        environment: "BW-UAT"
        resourceGroupName: 'rg-uat-ase-bw'
        location: 'australiasoutheast'
        bicepParams: 'uat-kv'
        deploymentMode: 'Incremental'
        deploymentName: 'bw-kv-uat-$(Build.BuildNumber)-$(System.StageAttempt)'

    deployRelease:
      - stageName: AZInfraKVPrd01
        displayName: "Deploy to Production"
        environment: "BW-Prod"
        resourceGroupName: 'rg-prd-ase-bw'
        location: 'australiasoutheast'
        bicepParams: 'prd-kv'
        deploymentMode: 'Incremental'
        deploymentName: 'bw-kv-prd-$(Build.BuildNumber)-$(System.StageAttempt)'
